config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :pages, only: :show
  resources :books, only: [:index, :show] do
    get 'search', on: :collection
    resources :chapters, only: [:index, :show] do
      resources :verses, only: [:index, :show] do
        get 'cross-references', to:'verses#cross_references', on: :member
      end
    end
  end

  resources :drills, only: [:index, :new, :create]
  resources :contacts, only: [:index, :new, :create], path: :contact
  resources :highlights, only: [:index, :update]
  resources :studies do
    get 'search', on: :collection
    put 'like', on: :member
    get 'books', on: :collection
    get 'chapters', on: :collection
    get 'verses', on: :collection
  end
  root to: 'site#index'
end

app/views/shared/_bible.html.slim
ul#bible-tabs.nav.nav-tabs.bible-tabs role="tablist"

  =render('shared/bible_tab', tab_id: "tab-blueprint", css_class: 'hidden tab-blueprint')
  =render('shared/bible_tab', tab_id: "tab-1", css_class: 'active')

  li#new-bible-tab.tab.new-bible-tab role="presentation"
    a href='#' +

  li.tab role="presentation"
    a.highlights-tab aria-controls="highlights" data-toggle="tab" data-loaded="false" data-url="#{highlights_path}" href="#highlights" role="tab" Highlights

#bible-tab-content.tab-content

  = render('shared/bible_tab_content', tab_id: "tab-blueprint", css_class: 'tab-pane-blueprint', vine: true)
  = render('shared/bible_tab_content', tab_id: "tab-1", css_class: 'active', vine: vine)

  #highlights.tab-pane.bible-tab-pane role="tabpanel"

app/views/shared/_bible_modal.html.slim
#bible-modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true" &times;
        h4.modal-title Select your verses
      .modal-body
      .modal-footer
        button.btn.btn-default data-dismiss="modal" type="button" Done

app/views/shared/_bible_tab.html.slim
li.tab.bible-tab role="presentation" data-tab-id="#{tab_id}" class="#{css_class}"
  a.tab-title> aria-controls="#{tab_id}" data-toggle="tab" href="##{tab_id}" role="tab" King James Bible

  span< style="position: absolute;right: 5px;top: 10px;"
    a.delete-tab href="#" data-tab-id="#{tab_id}" x

app/views/shared/_bible_tab_content.html.slim
.tab-pane.bible-tab-pane role="tabpanel" id="#{tab_id}" class="#{css_class}"

  .container-fluid.vine class="#{'hidden' unless vine }"

    .search

      = form_tag search_books_path, method: :get, remote: true, class: 'search-form', id: "search-#{tab_id}" do
        = text_field_tag :q, params[:q], class: 'form-control input-lg clearable', placeholder: 'Keyword Search'
        = content_tag :label, class: 'testament' do
          = check_box_tag 'old_testament', 'yes', params[:old_testament] || true
          small old
        = content_tag :label, class: 'testament' do
          = check_box_tag 'new_testament', 'yes', params[:new_testament] || true
          small new

      hr
      .row
        .col-xs-12
          .search-results.hidden

    ul.bible.contents.nav.nav-tabs role="tablist"
      li.active.tab.old role="presentation"
        a aria-controls="old" data-toggle="tab" href="#old-#{tab_id}" role="tab" Old
      li.tab.new role="presentation"
        a aria-controls="new" data-toggle="tab" href="#new-#{tab_id}" role="tab" New

    .tab-content.bible.contents
      .tab-pane.old.active role="tabpanel" id="old-#{tab_id}"
        .row
          = render partial: "shared/old_testament_books"
      .tab-pane.new role="tabpanel" id="new-#{tab_id}"
        .row
          = render partial: "shared/new_testament_books"
        .row
          .col-xs-12
            .legend<
            small
              i
                | Technically old testament. See&nbsp;
                a href="/books/hebrews/chapters/9/verses/16,17" here.

  .container-fluid.branches class="#{'hidden' if vine }"
    =yield :tab_content

app/views/shared/_book_chapters_menu.html.slim
/ #book-chapters-menu.hidden
/   .row
/     - @chapter.book_chapters.each do |chapter|
/       .col-xs-2
/         = link_to chapter.number, book_chapter_path(book_id: @chapter.book_permalink, id: chapter.number), remote: true

app/views/shared/_books_menu.html.slim
/ #books-menu.hidden
/   .row
/     .col-xs-12
/       = link_to "Search", books_path
/   .row
/     .col-xs-6
/       .row
/         - Book.old_paths.each do |book|
/           .col-xs-6
/             = link_to book[:name], book[:path], remote: true, class: 'tab-link'
/     .col-xs-6
/       .row
/         - Book.new_paths.each do |book|
/           .col-xs-6
/             = link_to book[:name], book[:path], remote: true, class: 'tab-link'

app/views/shared/_highlights.js.erb
<% @highlight_verse_ids.each do |verse_id| %>
    $('span.verse[data-verse-id="<%= verse_id %>"]').addClass('selected').next('a.verse-link').removeClass('hidden');
<% end %>

app/views/shared/_new_testament_books.html.slim
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/matthew/chapters"  Matthew
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/mark/chapters"  Mark
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/luke/chapters"  Luke
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/john/chapters"  John
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/acts/chapters"  Acts
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/romans/chapters"  Romans
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/1-corinthians/chapters"  1 Corinthians
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/2-corinthians/chapters"  2 Corinthians
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/galatians/chapters"  Galatians
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/ephesians/chapters"  Ephesians
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/philippians/chapters"  Philippians
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/colossians/chapters"  Colossians
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/1-thessalonians/chapters"  1 Thessalonians
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/2-thessalonians/chapters"  2 Thessalonians
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/1-timothy/chapters"  1 Timothy
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/2-timothy/chapters"  2 Timothy
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/titus/chapters"  Titus
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/philemon/chapters"  Philemon
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/hebrews/chapters"  Hebrews
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/james/chapters"  James
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/1-peter/chapters"  1 Peter
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/2-peter/chapters"  2 Peter
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/1-john/chapters"  1 John
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/2-john/chapters"  2 John
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/3-john/chapters"  3 John
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/jude/chapters"  Jude
.col-xs-6.col-sm-3
  .book
    a.z-index-100.tab-link data-remote="true" href="/books/revelation/chapters"  Revelation

app/views/shared/_old_testament_books.html.slim
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/genesis/chapters"  Genesis
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/exodus/chapters"  Exodus
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/leviticus/chapters"  Leviticus
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/numbers/chapters"  Numbers
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/deuteronomy/chapters"  Deuteronomy
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/joshua/chapters"  Joshua
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/judges/chapters"  Judges
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/ruth/chapters"  Ruth
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/1-samuel/chapters"  1 Samuel
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/2-samuel/chapters"  2 Samuel
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/1-kings/chapters"  1 Kings
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/2-kings/chapters"  2 Kings
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/1-chronicles/chapters"  1 Chronicles
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/2-chronicles/chapters"  2 Chronicles
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/ezra/chapters"  Ezra
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/nehemiah/chapters"  Nehemiah
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/esther/chapters"  Esther
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/job/chapters"  Job
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/psalms/chapters"  Psalms
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/proverbs/chapters"  Proverbs
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/ecclesiastes/chapters"  Ecclesiastes
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/song-of-solomon/chapters"  Song of Solomon
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/isaiah/chapters"  Isaiah
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/jeremiah/chapters"  Jeremiah
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/lamentations/chapters"  Lamentations
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/ezekiel/chapters"  Ezekiel
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/daniel/chapters"  Daniel
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/hosea/chapters"  Hosea
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/joel/chapters"  Joel
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/amos/chapters"  Amos
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/obadiah/chapters"  Obadiah
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/jonah/chapters"  Jonah
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/micah/chapters"  Micah
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/nahum/chapters"  Nahum
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/habakkuk/chapters"  Habakkuk
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/zephaniah/chapters"  Zephaniah
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/haggai/chapters"  Haggai
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/zechariah/chapters"  Zechariah
.col-xs-6.col-sm-3
  .book.old
    a.z-index-100.tab-link data-remote="true" href="/books/malachi/chapters"  Malachi