config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :pages, only: :show
  resources :books, only: [:index, :show] do
    get 'search', on: :collection
    resources :chapters, only: [:index, :show] do
      resources :verses, only: [:index, :show] do
        get 'cross-references', to:'verses#cross_references', on: :member
      end
    end
  end

  resources :drills, only: [:index, :new, :create]
  resources :contacts, only: [:index, :new, :create], path: :contact
  resources :highlights, only: [:index, :update]
  resources :studies do
    get 'search', on: :collection
    put 'like', on: :member
    get 'books', on: :collection
    get 'chapters', on: :collection
    get 'verses', on: :collection
  end
  root to: 'site#index'
end

app/models/study.rb
class Study < ActiveRecord::Base

  acts_as_votable
  is_impressionable counter_cache: true, column_name: :cached_views_total
  include PgSearch
  pg_search_scope :search_by_keyword, against: [:title, :description]

  has_permalink(:title, true)

  belongs_to :user
  has_many :sections, dependent: :destroy

  accepts_nested_attributes_for :sections, allow_destroy: true

  validates_presence_of :title, :description

  scope :active, ->{ where(active: true) }
  scope :recent, ->{ active.order(created_at: :desc) }
  scope :popular, ->{ active.where("cached_votes_up > 0").order(cached_weighted_average: :desc) }
  scope :mine, ->(user_id){ where(user_id: user_id).order(created_at: :desc) }

  def to_param
    permalink
  end

end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController

  load_and_authorize_resource find_by: :permalink
  skip_authorize_resource only: [:index, :show, :books, :chapters, :verses, :search]
  protect_from_forgery except: :index

  # GET /studies
  # GET /studies.json
  def index
    @page_title = "Bible Studies"
    @page_description = "Browse Bible studies by recent, most popular and liked."
    @type = params[:type].try(:downcase)
    case @type
      when "popular"
        @studies = Study.popular.page(params[:page])
      when "liked"
        @studies = current_user ? current_user.get_voted(Study).page(params[:page]) : Kaminari.paginate_array([]).page(params[:page])
      when "mine"
        @studies = current_user ? Study.mine(current_user.id).page(params[:page]) : Kaminari.paginate_array([]).page(params[:page])
      else
        @studies = Study.recent.page(params[:page])
    end
  end

  def books
    @old = Book.old_testament
    @new = Book.new_testament
  end

  def chapters
    @book = Book.find_by_permalink(params[:book_id])
    add_breadcrumb @book.name, :books_studies_path, title: "Books", remote: true
    add_breadcrumb "Chapters", chapters_studies_path(book_id: @book.permalink), title: "Chapters", remote: true
    @chapters = @book.chapters
  end

  def verses
    @book = Book.find_by_permalink(params[:book_id])
    @chapter = @book.chapters.find_by_number(params[:chapter_number])
    add_breadcrumb @book.name, :books_studies_path, title: "Books", remote: true
    add_breadcrumb "Chapter #{@chapter.number}", chapters_studies_path(book_id: @book.permalink), title: "Chapter #{@chapter.number}", remote: true
    @verses = @chapter.verses.reorder(id: :asc)
    @prev_chapter = @chapter.prev
    @next_chapter = @chapter.next
  end

  def search
    if Rails.env.production?
      @studies = Study.search_by_keyword(params[:q]).page(params[:page])
    else
      @studies = Study.where('title like :keyword or description like :keyword', keyword: "%#{params[:q]}%").page(params[:page])
    end
  end

  def like
    current_user.voted_up_on?(@study) ? @study.unliked_by(current_user) : @study.liked_by(current_user)
    respond_to do |format|
      format.js
    end
  end

  # def dislike
  #   current_user.voted_down_on?(@card) ? @card.undisliked_by(current_user) : @card.disliked_by(current_user)
  #   respond_to do |format|
  #     format.js
  #   end
  # end

  # GET /studies/1
  # GET /studies/1.json
  def show
    @page_title = @study.title
    @page_description = @study.description
    impressionist(@study, unique: [:session_hash]) #track page view count
  end

  # GET /studies/new
  def new
    @study = Study.new
    @study.sections.build
  end

  # GET /studies/1/edit
  def edit
  end

  # POST /studies
  # POST /studies.json
  def create
    @study.user = current_user

    respond_to do |format|
      if @study.save
        format.html { redirect_to @study, notice: 'Study was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /studies/1
  # PATCH/PUT /studies/1.json
  def update
    respond_to do |format|
      if @study.update(study_params)
        format.html { redirect_to @study, notice: 'Study was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /studies/1
  # DELETE /studies/1.json
  def destroy
    @study.destroy
    respond_to do |format|
      format.html { redirect_to studies_url, notice: 'Study was successfully destroyed.' }
    end
  end

  private

    def study_params
      params.require(:study).permit(
        [
          :title, :description,
          sections_attributes: [
            :id, :study_id, :_destroy, :title, :notes, :position,
            section_verses_attributes: [:id, :_destroy, :position, :verse_id]
          ]
        ]
      )
    end
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/studies/_books.html.slim
.bible-tab-pane.active

  .vine

    h1 King James Bible

    = form_tag search_books_path, method: :get, remote: true, id: 'search-form' do
      = text_field_tag :q, params[:q], class: 'form-control input-lg clearable', placeholder: 'Keyword Search'

    hr
    .row
      .col-xs-12
        #search-results.search-results.hidden

    ul#books-nav.bible.nav.nav-tabs role="tablist"
      li.active.tab role="presentation"
        a aria-controls="old" data-toggle="tab" href="#old" role="tab" Old
      li.tab role="presentation"
        a aria-controls="new" data-toggle="tab" href="#new" role="tab" New

    .tab-content.bible
      #old.tab-pane.fade.in.active role="tabpanel"
        .row
          - @old.each do |book|
            .col-xs-6.col-sm-3
              .book= link_to book.name, chapters_studies_path(book_id: book.permalink), remote: true, class: 'z-index-100'
      #new.tab-pane.fade role="tabpanel"
        .row
          - @new.each do |book|
            .col-xs-6.col-sm-3
              .book= link_to book.name, chapters_studies_path(book_id: book.permalink), remote: true, class: 'z-index-100'

  .branches

app/views/studies/_chapters.html.slim
h1 #{@book.name} chapters

ol.breadcrumb.sticky
  = render_breadcrumbs tag: :li, separator: ''

ul.list-inline.chapters
  - @chapters.each do |chapter|
    li
      =link_to chapter.number, verses_studies_path(book_id: @book.permalink, chapter_number: chapter.number), class: 'chapter z-index-100', remote: true

app/views/studies/_form.html.slim
= render 'shared/bible_modal'

= simple_form_for(@study, html: { class: 'form-horizontal' }, wrapper: :study_form) do |f|
  = f.error_notification
  = f.input :title, placeholder: "Give your study a title"
  = f.input :description, as: :summernote, wrapper: :full_size, input_html: {value: f.object.description || 'Give your study a good description here.'}
  #sections.panel-group.sortable role="tablist" aria-multiselectable="true"
    = f.simple_fields_for :sections do |section|
      = render 'section_fields', f: section

  p.links
    = link_to_add_association ' + add new section', f, :sections, data: { "association-insertion-node" => '#sections', "association-insertion-method" => 'append' }

  .form-group
    .col-sm-6
      .well.well-sm
        = f.button :submit, class: 'btn btn-primary', data: { disable_with: 'Updating...' }
        - unless @study.new_record?
          .pull-right
            small<= link_to "Delete Study", study_path(@study), method: :delete, data: { confirm: 'Are you sure you want to DELETE this study?'}
          .clearfix

= content_for :footer do
  = javascript_include_tag 'studies_form'

app/views/studies/_section_verse_fields.html.slim
li.nested-fields.handle
  span.verse-title=f.object.try(:verse_title)
  small<= link_to_remove_association "remove verse", f, class: 'remove-verse', data: { "verse-id" => f.object.try(:verse_id)}
  br
  span.verse-text=f.object.try(:verse_text)
  = f.input :position, as: :hidden, input_html: { class: 'position' }
  = f.input :verse_id, as: :hidden, input_html: { class: 'verse-id' }

app/views/studies/_studies.html.slim
- if @studies.present?
  - @studies.each do |study|
    = render study
- else
  .row style="margin-top: 20px;"
    .col-xs-12
      i
        span> No Bible Studies at the moment.
        - unless current_user
          = link_to "Login", new_user_session_path
          span< to create one.

app/views/studies/_verses.html.slim
=link_to "<", verses_studies_path(book_id: @prev_chapter.book_permalink, chapter_number: @prev_chapter.number), class: 'prev', remote: true
=link_to ">", verses_studies_path(book_id: @next_chapter.book_permalink, chapter_number: @next_chapter.number), class: 'next', remote: true

.row
  .col-xs-12.col-sm-10
    h1
      =@chapter.title

ol.breadcrumb.sticky
  = render_breadcrumbs tag: :li, separator: ''

ol.chapter.verses
  - @verses.each do |verse|
    li.verse value="#{verse.number}" data-verse-id="#{verse.id}" data-verse-title="#{verse.title}" #{verse.text}

app/views/studies/books.js.erb
$("#bible-modal .modal-body").html("<%= j render('books') %>").data('loaded', true);

app/views/studies/edit.html.slim
h1 Editing "#{@study.title}"

ul.breadcrumb
  li= link_to 'Bible Studies', studies_path
  li= link_to @study.title, study_path(@study)

== render 'form'

app/views/studies/index.html.slim
h1
  | Bible Studies
  - if current_user
    small<
      = link_to "Create a Bible Study", new_study_path

= form_tag search_studies_path, method: :get, remote: true, id: 'search-form' do
  = text_field_tag :q, params[:q], class: 'form-control input-lg clearable', placeholder: 'Keyword Search'

hr
.row
  .col-xs-12
    #search-results.hidden

ul#studies-nav.studies.contents.nav.nav-tabs role="tablist"
  li.active.tab role="presentation"
    a href="#{studies_path(format: :js)}" aria-controls="recent" data-toggle="tabajax" data-target="#recent" role="tab" Recent
  li.tab role="presentation"
    a href="#{studies_path(type: "popular", format: :js)}" aria-controls="popular" data-toggle="tabajax" data-target="#popular" role="tab" Popular
  li.tab role="presentation"
    a href="#{studies_path(type: "liked", format: :js)}" aria-controls="liked" data-toggle="tabajax" data-target="#liked" role="tab" Liked
  li.tab role="presentation"
    a href="#{studies_path(type: "mine", format: :js)}" aria-controls="mine" data-toggle="tabajax" data-target="#mine" role="tab" My Studies

.tab-content.contents
  #recent.tab-pane.fade.in.active role="tabpanel"
    = render 'studies'
  #popular.tab-pane.fade role="tabpanel"
  #liked.tab-pane.fade role="tabpanel"
  #mine.tab-pane.fade role="tabpanel"

app/views/studies/like.js.erb
$('span.likes[data-study-id="<%= @study.id %>"]').html('<%= @study.get_likes.size %>');

app/views/studies/new.html.slim
h1 New Bible Study
.row
  .col-xs-12
    p Bible Studies are composed of "sections".  Within each section you can add verses and expound upon them in the notes field.  You can add multiple sections to a study and each section can have multiple verses.

ul.breadcrumb
  li= link_to 'Bible Studies', studies_path
  li.active New Bible Study

== render 'form'

app/views/studies/search.js.erb
$("html, body").scrollTop(0);
$("#bible-modal .modal-body").scrollTop(0);
Search.destroyInfiniteScroll(); // order important here
$('#search-results').html('<%= j(render('search')) %>').append('<%= j(render('search_paginate')) %>');
Search.initInfiniteScroll();

app/views/studies/show.html.slim
h1=@study.title
.row
  .col-xs-6
    .pull-left
      ul.study-details style="font-size: large;"
        li
          = image_tag @study.user.avatar(:micro)
          span<=@study.user.name
        li #{time_ago_in_words(@study.created_at)} ago
        li= social_share_button_tag(@study.title, url: study_url(@study))

  .col-xs-6
    .pull-right
      p
        span.view_counts< style="vertical-align: text-bottom;" #{@study.cached_views_total} views
        span.text-muted<> |
        - if current_user
          = link_to like_study_path(@study, format: :js), remote: true, method: :put, class: 'like' do
            span.fa.fa-thumbs-o-up
        - else
          span.fa.fa-thumbs-o-up
        span.likes< data-study-id="#{@study.id}" #{@study.get_likes.size}
.clearfix
ul.breadcrumb
  li= link_to 'Bible Studies', studies_path
  li.active=@study.title
  - if can?(:edit, @study)
    li=link_to "Edit", edit_study_path(@study)

.row
  .col-xs-12
    p=@study.description.html_safe

#accordion.panel-group aria-multiselectable="true" role="tablist"
  - @study.sections.each_with_index do |section, index|
    .panel.panel-default
      .panel-heading role="tab" id="section-#{section.id}"
        h4.panel-title
          a aria-controls="collapse-#{section.id}" aria-expanded="#{index==0 ? 'true' : 'false'}" data-parent="#accordion" data-toggle="collapse" href="#collapse-#{section.id}" role="button"
            = section.formatted_title
      .panel-collapse.collapse aria-labelledby="section-#{section.id}" role="tabpanel" id="collapse-#{section.id}" class="#{'in' if index==0}"
        .panel-body
          - if section.verses.present?
            .well.well-sm
              ul.list-unstyled
                - section.verses.each do |verse|
                  li
                    p
                      = link_to verse.title, book_chapter_path(book_id: verse.book_permalink, id: verse.chapter_number), target: :blank
                      br
                      =verse.text
          .row
            .col-xs-12
              = section.notes.html_safe

app/views/studies/verses.js.erb
$("#bible-modal .modal-body").html("<%= j render('verses') %>").scrollTop(0);

//load the selected verses from the active section into the modal
var section_verse_ids = $("section.active").data('verse-ids') || [];
$("#bible-modal .modal-body span.verse.selected").removeClass('selected');
$.each(section_verse_ids, function(index, verse_id){
    $("#bible-modal .modal-body li.verse[data-verse-id="+verse_id+"]").addClass('selected');
});