config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :pages, only: :show
  resources :books, only: [:index, :show] do
    get 'search', on: :collection
    resources :chapters, only: [:index, :show] do
      resources :verses, only: [:index, :show] do
        get 'cross-references', to:'verses#cross_references', on: :member
      end
    end
  end

  resources :drills, only: [:index, :new, :create]
  resources :contacts, only: [:index, :new, :create], path: :contact
  resources :highlights, only: [:index, :update]
  resources :studies do
    get 'search', on: :collection
    put 'like', on: :member
    get 'books', on: :collection
    get 'chapters', on: :collection
    get 'verses', on: :collection
  end
  root to: 'site#index'
end

app/models/book.rb
class Book < ActiveRecord::Base

  has_many :chapters
  scope :old_testament, ->{where("id < 40").order(id: :asc) }
  scope :new_testament, ->{where("id > 39").order(id: :asc) }

  serialize :abbreviations, Array

  def to_param
    permalink
  end

  def abbreviation(position=:first)
    abbreviations.send(:try, position)
  end

  def old?
    id <= 43
  end

  def new?
    id > 39
  end

  def first_chapter
    chapters.first
  end

  def first_chapter_number
    first_chapter.try(:number)
  end

end

app/controllers/books_controller.rb
class BooksController < KjController

  def index
    @page_title = "King James Bible"
  end

  def show
    @book = Book.includes(:chapters).where(permalink: params[:id]).first
    @page_title = @book.name
    add_breadcrumb @book.name, :books_path, title: "Books", remote: true, class: 'tab-link'
  end

  def search
    if Rails.env.production?
      @verses = Verse.includes(chapter: :book).where('text ~* ?', '\y%s\y' % params[:q])
    else
      @verses = Verse.includes(chapter: :book).where('text like ?', "%#{params[:q]}%")
    end
    @verses = @verses.old_testament if params[:old_testament].present? && !params[:new_testament]
    @verses = @verses.new_testament if params[:new_testament].present? && !params[:old_testament]
    @verses = @verses.order(id: :asc).page params[:page]
    @page_title = "Search: #{params[:q]}"
    respond_to do |format|
      format.js
      format.html { render 'search', layout: false }
    end
  end

end

app/views/books/_book.html.slim
.col-xs-6.col-sm-3
  .book class="#{'old' if book.old?}"
    = link_to book.name, book_chapters_path(book_id: book.permalink), remote: true, class: 'z-index-100 tab-link'

app/views/books/_search.html.slim
- if @verses.present?
  .row
    .col-xs-12
      p
        i #{@verses.total_count} results

  - @verses.each do |verse|
    .row.search-result
      .col-xs-12
        p
          = link_to verse.title, book_chapter_verse_path(book_id: verse.book_permalink, chapter_id: verse.chapter_number, id: verse.number), class: 'verse search-result tab-link', data: { "verse-id" => verse.id, "verse-title" => verse.title, "verse-text" => verse.text }, remote: true
          br
          span.verse-text= verse.text
- else
  .row
    .col-xs-12
      i No results

app/views/books/index.html.slim
= render 'shared/bible', vine: true

app/views/books/index.js.erb
var $tabPane = $('.bible-tab-pane.active');

document.title = "<%= display_title(default_meta_tags) %>";
window.scrollTo(0, 0);

$tabPane.attr('data-next-path', '');
$tabPane.attr('data-prev-path', '');

$tabPane.find('.branches').addClass('hidden');
$tabPane.find('.vine').removeClass('hidden');

$('li.bible-tab.active a.tab-title').text('<%= @page_title %>');

Bible.init();

app/views/books/search.html.slim
= render('search')

app/views/books/search.js.erb
$("html, body").scrollTop(0);
$("#bible-modal .modal-body").scrollTop(0);

// order important here
Search.destroyInfiniteScroll();

var $tabPane = $('.bible-tab-pane.active');
$tabPane.find('.branches').addClass('hidden');
$tabPane.find('.search-results').html('<%= j(render('search')) %>').append('<%= j(render('search_paginate')) %>');
$tabPane.find('.vine').removeClass('hidden');

Search.initInfiniteScroll();

$('li.bible-tab.active a.tab-title').text('<%= @page_title %>');

app/views/books/show.html.slim
= render 'shared/bible', vine: true

app/views/books/show.js.erb
$('.bible-tab-pane.active .vine').removeClass('hidden');
$('.bible-tab-pane.active .branches').html('<%= j(render('show')) %>').addClass('hidden');

document.title = "<%= display_title(default_meta_tags) %>";

$('li.bible-tab.active a.tab-title').text('<%= @page_title %>');