config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :pages, only: :show
  resources :books, only: [:index, :show] do
    get 'search', on: :collection
    resources :chapters, only: [:index, :show] do
      resources :verses, only: [:index, :show] do
        get 'cross-references', to:'verses#cross_references', on: :member
      end
    end
  end

  resources :drills, only: [:index, :new, :create]
  resources :contacts, only: [:index, :new, :create], path: :contact
  resources :highlights, only: [:index, :update]
  resources :studies do
    get 'search', on: :collection
    put 'like', on: :member
    get 'books', on: :collection
    get 'chapters', on: :collection
    get 'verses', on: :collection
  end
  root to: 'site#index'
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index
    @page_title = "Online Bible Drill"
    @page_description = "Hone your verse finding skill with our innovative, online Bible drill.  Create and share Bible studies or read the King James Bible online."
  end

end

app/views/site/index.html.slim
.row
  .col-xs-12.col-sm-4
    .panel.panel-default
      = link_to drills_path do
        .panel-body
          span.fa.fa-hourglass-1.fa-5x
          h1 Bible Drill
  .col-xs-12.col-sm-4
    .panel.panel-default
      = link_to books_path do
        .panel-body
          span.fa.fa-book.fa-5x
          h1 Read the Bible
  .col-xs-12.col-sm-4
    .panel.panel-default
      = link_to studies_path do
        .panel-body
          span.fa.fa-mortar-board.fa-5x
          h1 Bible Studies

app/views/site/random_verse.js.erb
$('#random-verse').data('verse-id', '<%= @verse.id%>').html('<%= j link_to(@verse.title, '#', class: 'refresh') %>');